### ISSUE TITLE
 TAG_BLOCKS[0x01430000] is wrong

### ISSUE THREAD

**Issue by klahnakoski** [mitchhentges/lcov-rs#1]
Excellent wiki! 

I think `TAG_BLOCKS[0x01430000] ` should read `TAG_BLOCKS[0x01410000]` as per https://github.com/gcc-mirror/gcc/blob/master/gcc/gcov-io.h#L231

**Comment by mitchhentges** [comment]
Great catch, thanks! Updated the wiki :)
